# Generated by Django 3.2.5 on 2021-07-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfilters',
            name='end_range',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventfilters',
            name='start_range',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
