# Generated by Django 3.2.5 on 2021-07-20 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20210719_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfilters',
            name='save_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('msg', models.TextField(blank=True, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_datetime'],
            },
        ),
    ]
